[package]
name = "orange-pi-monitor"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cli"
path = "src/cli.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sysinfo = "0.30"
systemstat = "0.2"
tokio = { version = "1", features = ["full"] }
